import { AxiosResponse } from "axios";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import qs from "qs";
import { useRouter } from "next/router";
import { fetchArticles, fetchCategories } from "../http";
import ArticleList from "../components/ArticleList";
import Tabs from "../components/Tabs";
import {
  ICategory,
  ICollectionResponse,
  IArticle,
  IPagination,
  IQueryOptions,
} from "../types";
import { debounce } from "../utils";
import Pagination from "../components/Pagination";

interface IPropTypes {
  categories: {
    items: ICategory[];
  };
  articles: {
    items: IArticle[];
    pagination: IPagination;
  };
}

const Home: NextPage<IPropTypes> = ({ categories, articles }) => {
  const router = useRouter();
  const { page, pageCount } = articles?.pagination;

  const handleSearch = (query: string) => {
    router.push(`/?search=${query}`);
  };

  return (
    <div>
      <Head>
        <title>Tech Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Tabs
        categories={categories?.items}
        handleOnSearch={debounce(handleSearch, 500)}
      />

      <ArticleList articles={articles?.items} />

      <Pagination page={page} pageCount={pageCount} />
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  // categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  // articles
  const options: Partial<IQueryOptions> = {
    populate: ["author.avatar"],
    sort: ["id:desc"],
    pagination: {
      page: query?.page ? +query.page : 1,
      pageSize: 10,
    },
  };

  if (query?.search) {
    options.filters = {
      title: {
        $containsi: query.search,
      },
    };
  }

  const queryString = qs.stringify(options);

  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> =
    await fetchArticles(queryString);

  return {
    props: {
      categories: {
        items: categories?.data || [],
      },
      articles: {
        items: articles?.data || [],
        pagination: articles?.meta?.pagination || {},
      },
    },
  };
};

export default Home;
